export const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#0b1020",
    color: "#edf2f7",
    padding: 24,
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    alignItems: "flex-start",
    marginBottom: 20,
  },
  h1: {
    margin: 0,
    fontSize: 28,
  },
  sub: {
    margin: "8px 0 0",
    color: "#a0aec0",
    maxWidth: 900,
    lineHeight: 1.5,
  },
  headerActions: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "1.35fr 1fr",
    gap: 16,
  },
  leftCol: {
    display: "grid",
    gap: 16,
    alignContent: "start",
  },
  rightCol: {
    display: "grid",
    gap: 16,
    alignContent: "start",
  },
  card: {
    background: "#111827",
    border: "1px solid #1f2937",
    borderRadius: 14,
    padding: 16,
    boxShadow: "0 8px 30px rgba(0,0,0,0.25)",
  },
  rowBetween: {
    display: "flex",
    justifyContent: "space-between",
    gap: 8,
    alignItems: "center",
    marginBottom: 10,
  },
  muted: {
    color: "#94a3b8",
    fontSize: 13,
  },
  mutedSmall: {
    color: "#94a3b8",
    fontSize: 12,
    marginTop: 2,
  },
  controls: {
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 12,
  },
  checkbox: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 14,
  },
  inlineField: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 14,
  },
  smallInput: {
    width: 72,
    background: "#0f172a",
    color: "#fff",
    border: "1px solid #334155",
    borderRadius: 8,
    padding: "6px 8px",
  },
  cmdkRoot: {
    border: "1px solid #243041",
    borderRadius: 12,
    overflow: "hidden",
    background: "#0f172a",
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    padding: "14px 16px",
    border: "none",
    outline: "none",
    background: "#0f172a",
    color: "#fff",
    fontSize: 15,
    borderBottom: "1px solid #1e293b",
  },
  list: {
    maxHeight: 620,
    overflow: "auto",
    padding: 8,
  },
  empty: {
    padding: 16,
    color: "#94a3b8",
  },
  item: {
    display: "flex",
    gap: 12,
    alignItems: "center",
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
    border: "1px solid #1f2937",
    background: "#111827",
    cursor: "pointer",
  },
  itemSelected: {
    border: "1px solid #3b82f6",
    background: "#0f1b34",
  },
  scoreBlock: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  scoreBadge: {
    borderRadius: 999,
    fontSize: 12,
    padding: "4px 10px",
    fontWeight: 700,
  },
  scoreGood: {
    background: "rgba(16,185,129,0.15)",
    color: "#6ee7b7",
  },
  scoreMid: {
    background: "rgba(245,158,11,0.15)",
    color: "#fcd34d",
  },
  scoreLow: {
    background: "rgba(148,163,184,0.15)",
    color: "#cbd5e1",
  },
  breakdown: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    fontSize: 12,
    color: "#cbd5e1",
    marginTop: 8,
  },
  signalList: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  signalPill: {
    borderRadius: 999,
    padding: "4px 8px",
    fontSize: 11,
    border: "1px solid #334155",
  },
  signalPillActive: {
    background: "rgba(56,189,248,0.14)",
    color: "#bae6fd",
    border: "1px solid rgba(56,189,248,0.35)",
  },
  signalPillMuted: {
    background: "rgba(148,163,184,0.08)",
    color: "#94a3b8",
    border: "1px solid rgba(148,163,184,0.2)",
  },
  metaRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    fontSize: 12,
    color: "#94a3b8",
    marginTop: 8,
  },
  pinButton: {
    background: "#1f2937",
    color: "#fff",
    border: "1px solid #374151",
    borderRadius: 8,
    padding: "8px 10px",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  scenarioWrap: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  scenarioButton: {
    background: "#0f172a",
    color: "#e2e8f0",
    border: "1px solid #334155",
    borderRadius: 999,
    padding: "8px 12px",
    cursor: "pointer",
    fontSize: 13,
  },
  codeInline: {
    color: "#93c5fd",
  },
  buttonRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 12,
  },
  button: {
    background: "#1d4ed8",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "9px 12px",
    cursor: "pointer",
  },
  buttonDanger: {
    background: "#b91c1c",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "9px 12px",
    cursor: "pointer",
  },
  pre: {
    margin: 0,
    background: "#0b1220",
    color: "#dbeafe",
    borderRadius: 10,
    padding: 12,
    fontSize: 12,
    maxHeight: 280,
    overflow: "auto",
    border: "1px solid #1e293b",
  },
  textarea: {
    width: "100%",
    minHeight: 220,
    boxSizing: "border-box",
    background: "#0b1220",
    color: "#dbeafe",
    border: "1px solid #334155",
    borderRadius: 10,
    padding: 12,
    fontSize: 12,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
  },
  details: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
  },
  detailWide: {
    gridColumn: "1 / -1",
  },
  kvLabel: {
    fontSize: 12,
    color: "#94a3b8",
    marginBottom: 4,
  },
  emptyBox: {
    padding: 12,
    borderRadius: 10,
    background: "#0b1220",
    color: "#94a3b8",
    border: "1px solid #1e293b",
  },
  listOl: {
    margin: "8px 0 0 18px",
    color: "#dbeafe",
    lineHeight: 1.7,
  },
};
